CREATE TABLE DB2INST1.LOAD_TEST_PERL
(
    ID                 SMALLINT     NOT NULL,
    SNAPSHOT_TIMESTAMP TIMESTAMP(6) NOT NULL,
    DBNAME             VARCHAR(50)  NOT NULL,
    DESCRIPTION        VARCHAR(500)
)
;

CREATE TABLE DB2INST1.LOAD_TEST_PERL_DETAILS
(
    ID            SMALLINT      NOT NULL,
    SP_NAME       VARCHAR(500),
    ROWS_RETURNED INTEGER,
    EXEC_IN_SEC   DECIMAL(10,6),
    FETCH_IN_SEC  DECIMAL(10,6)
)

;
